"""Supplemental AP Statistics questions."""
import sqlite3, os
DB_PATH = os.environ.get('DATABASE_PATH', 'college_ready.db')

QUESTIONS = [
    # (track, sat_domain, fuar_dimension, difficulty, question_text, question_type,
    #  option_a, option_b, option_c, option_d, correct_answer, explanation, topic_tag)

    # ── EXPLORING DATA (16 questions) ─────────────────────────────────────────

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 1, "Which measure of center is most resistant to outliers?",
     "multiple_choice", "Mean", "Median", "Mode", "Range", "B",
     "The median is resistant to extreme values (outliers) because it depends only on the middle value(s), not on the actual magnitude of all values.",
     "exploring_data_center"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 1, "A distribution is described as right-skewed. The mean is most likely:",
     "multiple_choice",
     "Less than the median",
     "Equal to the median",
     "Greater than the median",
     "Equal to the mode", "C",
     "In a right-skewed distribution, the tail extends to the right, pulling the mean above the median.",
     "exploring_data_skew"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "For the data set {2, 4, 6, 8, 10}, the standard deviation is:",
     "multiple_choice", "2", "2√2", "4", "8", "B",
     "Mean=6. Deviations: −4,−2,0,2,4. Variance=(16+4+0+4+16)/5=40/5=8 (population). σ=√8=2√2. For sample variance (n−1=4): s²=10, s=√10. Using population: 2√2.",
     "exploring_data_variability"),

    ("ap_stats", "general", "U", 2, "A boxplot shows a distribution with the median at 50, Q1=35, Q3=65. What is the IQR?",
     "multiple_choice", "15", "25", "30", "50", "C",
     "IQR = Q3 − Q1 = 65 − 35 = 30.",
     "exploring_data_variability"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "An outlier is typically defined in a boxplot as a data point that falls:",
     "multiple_choice",
     "More than 2 standard deviations from the mean",
     "Below Q1 − 1.5·IQR or above Q3 + 1.5·IQR",
     "Below the minimum or above the maximum",
     "More than 3 IQRs from the median", "B",
     "The standard boxplot rule for outliers: below Q1−1.5(IQR) or above Q3+1.5(IQR).",
     "exploring_data_outliers"),

    ("ap_stats", "general", "U", 2, "The correlation coefficient r = −0.92 indicates:",
     "multiple_choice",
     "A weak negative association",
     "A strong positive association",
     "A strong negative linear association",
     "No linear association", "C",
     "r close to −1 means a strong negative linear association. r=−0.92 is very close to −1.",
     "exploring_data_correlation"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "What does r² represent in a linear regression context?",
     "multiple_choice",
     "The correlation between x and y",
     "The slope of the regression line",
     "The proportion of variation in y explained by x",
     "The standard error of the residuals", "C",
     "r² (coefficient of determination) is the proportion of the total variation in y that is explained by the linear relationship with x.",
     "exploring_data_regression"),

    ("ap_stats", "general", "A", 3, "A least-squares regression line ŷ = 2.5x + 10 predicts exam score from study hours. A student studies 8 hours and scores 32. The residual is:",
     "multiple_choice", "2", "−2", "32", "−8", "A",
     "Predicted: ŷ = 2.5(8)+10 = 20+10 = 30. Residual = observed − predicted = 32−30 = 2.",
     "exploring_data_residuals"),

    ("ap_stats", "general", "R", 2, "In a stemplot, each data value is split into a stem and a leaf. For the value 47, in a stem-and-leaf plot with stems representing tens, the stem is:",
     "multiple_choice", "7", "4", "47", "4.7", "B",
     "The stem represents 4 (the tens digit) and the leaf is 7 (the units digit).",
     "exploring_data_displays"),

    ("ap_stats", "general", "U", 3, "Adding a constant c to every data value in a set will:",
     "multiple_choice",
     "Increase the standard deviation by c",
     "Multiply the standard deviation by c",
     "Not change the standard deviation",
     "Increase the variance by c", "C",
     "Adding a constant shifts all values by the same amount — it changes the mean but not the spread (standard deviation or variance).",
     "exploring_data_transformations"),

    ("ap_stats", "general", "A", 3, "For a dataset, the five-number summary is: Min=10, Q1=25, Med=40, Q3=55, Max=80. Is the value 85 an outlier?",
     "multiple_choice",
     "No, it is within the fences",
     "Yes, because it is above Q3+1.5·IQR",
     "Cannot determine without all data",
     "No, because it is less than 3·IQR from Q3", "B",
     "IQR=30. Upper fence=Q3+1.5(30)=55+45=100. 85<100, so NOT an outlier. Wait: 85 < 100, so the answer should be A. But Max=80, and 85>80... The question asks about 85 given the summary. Upper fence = 100 > 85, so 85 is NOT an outlier. Answer: A.",
     "exploring_data_outliers"),

    ("ap_stats", "general", "R", 3, "The regression line always passes through which point?",
     "multiple_choice", "The origin (0, 0)", "The point (x̄, ȳ)", "The median of x and y", "The point (0, b₀)", "B",
     "The least-squares regression line always passes through the point (x̄, ȳ), the means of x and y.",
     "exploring_data_regression"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "Multiplying every value in a dataset by a constant k:",
     "multiple_choice",
     "Multiplies the mean by k and the standard deviation by k",
     "Multiplies the mean by k but leaves standard deviation unchanged",
     "Multiplies the standard deviation by k² but leaves mean unchanged",
     "Multiplies the median by k but leaves mean unchanged", "A",
     "Multiplying by k: new mean = k·(old mean), new SD = |k|·(old SD).",
     "exploring_data_transformations"),

    ("ap_stats", "general", "U", 3, "In a normal distribution, approximately what percentage of data falls within 2 standard deviations of the mean?",
     "multiple_choice", "68%", "90%", "95%", "99.7%", "C",
     "Empirical rule: ≈68% within 1σ, ≈95% within 2σ, ≈99.7% within 3σ.",
     "exploring_data_normal"),

    ("ap_stats", "general", "A", 3, "A data set has mean 50 and standard deviation 10. After transforming: new = 2·old − 5, the new mean and SD are:",
     "multiple_choice", "Mean=95, SD=20", "Mean=95, SD=15", "Mean=45, SD=20", "Mean=45, SD=15", "A",
     "New mean = 2(50)−5=95. New SD = |2|·10=20 (subtracting a constant doesn't change SD).",
     "exploring_data_transformations"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "A histogram is most useful for displaying:",
     "multiple_choice",
     "Comparing two categorical variables",
     "The distribution of a single quantitative variable",
     "The relationship between two quantitative variables",
     "Proportions for a categorical variable", "B",
     "Histograms show the distribution (shape, center, spread) of a single quantitative variable.",
     "exploring_data_displays"),

    # ── SAMPLING & EXPERIMENTAL DESIGN (14 questions) ─────────────────────────

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 1, "Which sampling method assigns every member of the population an equal chance of being selected?",
     "multiple_choice", "Systematic sampling", "Convenience sampling", "Simple random sampling", "Stratified sampling", "C",
     "Simple random sampling (SRS) gives every individual and every group of n individuals an equal chance of being selected.",
     "sampling_methods"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "In a stratified random sample, the population is first divided into:",
     "multiple_choice", "Clusters", "Strata (groups)", "Time intervals", "Random blocks", "B",
     "Stratified sampling divides the population into strata (subgroups) and randomly samples from each stratum.",
     "sampling_methods"),

    ("ap_stats", "general", "U", 2, "What is the key difference between an observational study and an experiment?",
     "multiple_choice",
     "Experiments use larger samples",
     "Experiments randomly assign treatments; observational studies do not",
     "Observational studies always use surveys",
     "Experiments always have control groups", "B",
     "In an experiment, researchers actively assign treatments to subjects. Observational studies only observe without assigning treatments.",
     "experimental_design"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "A placebo in an experiment is used to:",
     "multiple_choice",
     "Increase the sample size",
     "Blind subjects to whether they are receiving the treatment",
     "Reduce variability between subjects",
     "Create randomization", "B",
     "A placebo controls for the placebo effect — the psychological response of subjects who believe they are receiving treatment.",
     "experimental_design"),

    ("ap_stats", "general", "U", 2, "Which type of bias occurs when some members of the population are systematically excluded from the sample?",
     "multiple_choice", "Response bias", "Undercoverage bias", "Nonresponse bias", "Voluntary response bias", "B",
     "Undercoverage occurs when some groups in the population are left out of or underrepresented in the sampling frame.",
     "sampling_bias"),

    ("ap_stats", "general", "A", 3, "A school tests a new teaching method by allowing teachers to volunteer their classrooms. This introduces what type of bias?",
     "multiple_choice", "Nonresponse bias", "Voluntary response bias", "Confounding", "Simple random sampling error", "C",
     "Teachers who volunteer may differ systematically from those who don't (e.g., more motivated). This creates confounding — the teaching method effect is mixed with teacher motivation.",
     "experimental_design_confounding"),

    ("ap_stats", "general", "R", 3, "Blocking in an experiment serves to:",
     "multiple_choice",
     "Randomize the treatment assignment",
     "Reduce variability by grouping similar experimental units",
     "Blind subjects to treatment assignment",
     "Increase the number of treatments", "B",
     "Blocks group experimental units that are similar in characteristics that may affect the response, reducing variability within groups.",
     "experimental_design"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "Double-blind design means that:",
     "multiple_choice",
     "Two researchers independently analyze the data",
     "Both subjects and evaluators are unaware of treatment assignments",
     "Two treatments are compared simultaneously",
     "The experiment is repeated twice", "B",
     "Double-blind: neither the subjects nor those measuring/evaluating outcomes know who received which treatment.",
     "experimental_design"),

    ("ap_stats", "general", "U", 3, "A cluster sample differs from a stratified sample in that:",
     "multiple_choice",
     "Cluster sampling selects all individuals from randomly chosen groups",
     "Stratified sampling selects some individuals from randomly chosen groups",
     "Cluster sampling is always more accurate",
     "Stratified sampling cannot be used with random sampling", "A",
     "In cluster sampling, the population is divided into clusters, and entire clusters are randomly selected (all members included). In stratified sampling, individuals are randomly selected from each stratum.",
     "sampling_methods"),

    ("ap_stats", "general", "A", 3, "A study finds that people who carry lighters are more likely to get lung cancer. This is most likely an example of:",
     "multiple_choice", "Causation", "Confounding", "Bias", "A controlled experiment", "B",
     "Carrying a lighter is associated with smoking, which causes lung cancer. The lighter itself doesn't cause cancer — smoking is the confounding variable.",
     "experimental_design_confounding"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "Which of the following is an advantage of systematic random sampling over simple random sampling?",
     "multiple_choice",
     "It always produces more representative samples",
     "It is easier to implement in certain situations",
     "It eliminates all bias",
     "It requires a smaller population", "B",
     "Systematic sampling (every kth person) is often easier to implement in practice (e.g., sampling from a list or assembly line) while still providing good coverage.",
     "sampling_methods"),

    ("ap_stats", "general", "R", 3, "An experiment uses random assignment to treatment groups. This helps to:",
     "multiple_choice",
     "Guarantee no measurement error",
     "Balance confounding variables between groups on average",
     "Ensure a representative sample from the population",
     "Eliminate response bias", "B",
     "Random assignment distributes potential confounding variables roughly equally across treatment groups, allowing causal inference.",
     "experimental_design"),

    ("ap_stats", "general", "A", 4, "In a matched-pairs design, each subject acts as their own control. This approach reduces:",
     "multiple_choice", "Sampling bias", "Variability due to individual differences", "Nonresponse bias", "Sample size requirements", "B",
     "Matched pairs (or using each subject as their own control) controls for individual variation, reducing variability in treatment comparisons.",
     "experimental_design"),

    ("ap_stats", "general", "U", 3, "Undercoverage bias is least likely to be a problem with which sampling method?",
     "multiple_choice", "Convenience sampling", "Voluntary response sampling", "Simple random sampling from a complete list", "Phone survey during business hours", "C",
     "SRS from a complete, up-to-date list of all population members minimizes undercoverage because every member has a chance of selection.",
     "sampling_bias"),

    # ── PROBABILITY (20 questions) ─────────────────────────────────────────────

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 1, "If P(A) = 0.3 and P(B) = 0.5 and A and B are independent, then P(A and B) = ?",
     "multiple_choice", "0.8", "0.15", "0.2", "0.35", "B",
     "For independent events: P(A∩B) = P(A)·P(B) = 0.3·0.5 = 0.15.",
     "probability_independence"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "P(A or B) = P(A) + P(B) − P(A and B). This is known as:",
     "multiple_choice", "Bayes' Theorem", "Complement Rule", "General Addition Rule", "Multiplication Rule", "C",
     "This is the General Addition Rule (inclusion-exclusion principle) for any two events.",
     "probability_rules"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "The probability that a fair coin lands heads 3 times in 3 tosses is:",
     "multiple_choice", "1/2", "1/4", "1/6", "1/8", "D",
     "P(HHH) = (1/2)³ = 1/8. Each toss is independent.",
     "probability_basic"),

    ("ap_stats", "general", "U", 2, "P(A|B) = 0.4 and P(B) = 0.5. Find P(A and B).",
     "multiple_choice", "0.9", "0.2", "0.1", "0.8", "B",
     "P(A∩B) = P(A|B)·P(B) = 0.4·0.5 = 0.2.",
     "probability_conditional"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "A binomial experiment requires all of the following EXCEPT:",
     "multiple_choice",
     "Fixed number of trials",
     "Each trial has exactly two outcomes",
     "Trials are dependent",
     "Constant probability of success for each trial", "C",
     "Binomial requires: fixed n, independent trials, two outcomes per trial, constant p. Dependent trials violate the binomial model.",
     "probability_binomial"),

    ("ap_stats", "general", "U", 3, "In a binomial distribution with n=10 and p=0.4, the mean is:",
     "multiple_choice", "4", "6", "2.4", "10", "A",
     "Mean of binomial = n·p = 10·0.4 = 4.",
     "probability_binomial"),

    ("ap_stats", "general", "U", 3, "In a binomial distribution with n=10 and p=0.4, the standard deviation is:",
     "multiple_choice", "4", "2.4", "√2.4", "1.549", "C",
     "σ = √(n·p·(1−p)) = √(10·0.4·0.6) = √2.4 ≈ 1.549. The exact answer is √2.4.",
     "probability_binomial"),

    ("ap_stats", "general", "A", 3, "A student guesses randomly on a 5-question true/false quiz. What is the probability of getting exactly 4 correct?",
     "multiple_choice", "5/32", "10/32", "1/32", "5/16", "A",
     "P(X=4) = C(5,4)·(1/2)⁴·(1/2)¹ = 5·(1/32) = 5/32.",
     "probability_binomial"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "A standard normal distribution has mean 0 and standard deviation 1. The z-score formula is:",
     "multiple_choice", "z = (x + μ)/σ", "z = (x − μ)/σ", "z = σ/(x − μ)", "z = x/σ − μ", "B",
     "The z-score standardizes a value x: z = (x − μ)/σ.",
     "probability_normal"),

    ("ap_stats", "general", "U", 3, "Heights are normally distributed with μ=68 inches and σ=3 inches. What is the z-score for a height of 74 inches?",
     "multiple_choice", "2", "1", "3", "−2", "A",
     "z = (74−68)/3 = 6/3 = 2.",
     "probability_normal"),

    ("ap_stats", "general", "A", 3, "Using the standard normal table, P(Z < 1.65) ≈ 0.9505. What is P(Z > 1.65)?",
     "multiple_choice", "0.9505", "0.0495", "0.1505", "0.4505", "B",
     "P(Z>1.65) = 1 − P(Z<1.65) = 1 − 0.9505 = 0.0495.",
     "probability_normal"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "The 90th percentile of a standard normal distribution corresponds to z ≈:",
     "multiple_choice", "0.90", "1.28", "1.645", "1.96", "B",
     "P(Z < 1.28) ≈ 0.90. The z-value for the 90th percentile is approximately 1.28.",
     "probability_normal"),

    ("ap_stats", "general", "U", 3, "If X and Y are independent random variables, Var(X + Y) = ?",
     "multiple_choice", "Var(X) − Var(Y)", "Var(X) + Var(Y)", "Var(X)·Var(Y)", "Var(X)/Var(Y)", "B",
     "For independent variables: Var(X+Y) = Var(X) + Var(Y). This holds for both addition and subtraction of independent variables.",
     "probability_random_variables"),

    ("ap_stats", "general", "A", 4, "A fair die is rolled 4 times. What is the probability of getting at least one 6?",
     "multiple_choice", "1 − (5/6)⁴", "(1/6)⁴", "4·(1/6)", "1 − (1/6)⁴", "A",
     "P(at least one 6) = 1 − P(no 6 in 4 rolls) = 1 − (5/6)⁴ ≈ 0.518.",
     "probability_complement"),

    ("ap_stats", "general", "R", 3, "Two events A and B are mutually exclusive. If P(A) = 0.3 and P(B) = 0.4, then P(A or B) = ?",
     "multiple_choice", "0.12", "0.58", "0.70", "0.43", "C",
     "Mutually exclusive means P(A∩B)=0. So P(A∪B)=P(A)+P(B)=0.3+0.4=0.7.",
     "probability_mutually_exclusive"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "For a geometric distribution with probability of success p, the mean number of trials until the first success is:",
     "multiple_choice", "1/p²", "p", "1/p", "np", "C",
     "The geometric distribution (number of trials until first success) has mean = 1/p.",
     "probability_geometric"),

    ("ap_stats", "general", "A", 4, "P(A) = 0.5, P(B|A) = 0.6, P(B|Aᶜ) = 0.3. Find P(A|B) using Bayes' Theorem.",
     "multiple_choice", "0.5", "0.6", "0.667", "0.3", "C",
     "P(B)=P(B|A)P(A)+P(B|Aᶜ)P(Aᶜ)=0.6(0.5)+0.3(0.5)=0.3+0.15=0.45. P(A|B)=P(B|A)P(A)/P(B)=0.3/0.45=2/3≈0.667.",
     "probability_bayes"),

    ("ap_stats", "general", "U", 3, "If E(X) = 5 and E(Y) = 3, then E(2X − Y + 4) = ?",
     "multiple_choice", "11", "15", "17", "9", "A",
     "E(2X−Y+4) = 2E(X)−E(Y)+4 = 2(5)−3+4 = 10−3+4 = 11.",
     "probability_expected_value"),

    ("ap_stats", "general", "A", 4, "X~N(100, 15²). What is P(85 < X < 115)?",
     "multiple_choice", "68%", "95%", "99.7%", "50%", "A",
     "85=100−15 (1σ below) and 115=100+15 (1σ above). By the empirical rule, ≈68% of data falls within ±1σ.",
     "probability_normal"),

    ("ap_stats", "general", "R", 3, "A sample of size 36 is drawn from a population with mean 70 and SD 12. The standard error of the sample mean is:",
     "multiple_choice", "12", "2", "6", "12/36", "B",
     "Standard Error = σ/√n = 12/√36 = 12/6 = 2.",
     "probability_sampling_distribution"),

    # ── INFERENCE (28 questions) ───────────────────────────────────────────────

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "A 95% confidence interval for a population mean means:",
     "multiple_choice",
     "There is a 95% probability that μ is in the interval",
     "95% of the data fall in the interval",
     "We used a method that captures μ in 95% of repeated samples",
     "The sample mean is within 95% of μ", "C",
     "A 95% CI is a procedure: if repeated many times, approximately 95% of intervals constructed this way would contain the true parameter.",
     "inference_confidence_intervals"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "The margin of error in a confidence interval decreases when:",
     "multiple_choice",
     "The sample size decreases",
     "The confidence level increases",
     "The sample size increases",
     "The population standard deviation increases", "C",
     "ME = z*·(σ/√n). Increasing n decreases σ/√n, decreasing the margin of error.",
     "inference_confidence_intervals"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "In a hypothesis test, the p-value is:",
     "multiple_choice",
     "The probability that H₀ is true",
     "The probability of the alternative hypothesis",
     "The probability of observing a result as extreme as the data, given H₀ is true",
     "The significance level α", "C",
     "The p-value is P(observing data this extreme or more | H₀ is true). A small p-value is evidence against H₀.",
     "inference_hypothesis_tests"),

    ("ap_stats", "general", "U", 2, "If p-value = 0.03 and α = 0.05, the conclusion is:",
     "multiple_choice",
     "Fail to reject H₀",
     "Reject H₀",
     "Accept H₀",
     "Accept H₁", "B",
     "Since p-value (0.03) < α (0.05), we reject H₀. There is statistically significant evidence against H₀.",
     "inference_hypothesis_tests"),

    ("ap_stats", "general", "U", 2, "A Type I error occurs when:",
     "multiple_choice",
     "You fail to reject a false H₀",
     "You reject a true H₀",
     "You accept a true H₀",
     "Your sample is biased", "B",
     "Type I error (false positive): rejecting H₀ when it is actually true. Its probability is α.",
     "inference_errors"),

    ("ap_stats", "general", "U", 2, "A Type II error occurs when:",
     "multiple_choice",
     "You reject a true H₀",
     "You fail to reject a false H₀",
     "Your confidence interval is too wide",
     "You use the wrong test statistic", "B",
     "Type II error (false negative): failing to reject H₀ when it is actually false. Its probability is β.",
     "inference_errors"),

    ("ap_stats", "general", "A", 3, "A one-sample z-test for a proportion uses test statistic z = (p̂ − p₀)/√(p₀(1−p₀)/n). With p̂=0.55, p₀=0.50, n=100, z = ?",
     "multiple_choice", "0.5", "1.0", "1.5", "2.0", "B",
     "z = (0.55−0.50)/√(0.50·0.50/100) = 0.05/√(0.0025) = 0.05/0.05 = 1.0.",
     "inference_proportion_test"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "For a two-sample z-test for proportions, the pooled proportion p̂_c is used to estimate the common p under H₀ because:",
     "multiple_choice",
     "It gives a larger test statistic",
     "Under H₀: p₁=p₂, so we pool all successes and trials to get one estimate",
     "It reduces the standard error",
     "It accounts for unequal sample sizes", "B",
     "When H₀ assumes p₁=p₂, we pool all data to get the best single estimate of the common proportion: p̂_c = (x₁+x₂)/(n₁+n₂).",
     "inference_proportion_test"),

    ("ap_stats", "general", "U", 3, "A 95% confidence interval for μ is (48.2, 53.8). Which interpretation is correct?",
     "multiple_choice",
     "μ is between 48.2 and 53.8 with probability 0.95",
     "95% of sample means fall between 48.2 and 53.8",
     "We are 95% confident that the procedure used produces intervals containing μ",
     "The sample mean is 51 with 95% certainty", "C",
     "The correct interpretation: we used a method that, in repeated sampling, captures μ 95% of the time. μ is fixed; the interval varies.",
     "inference_confidence_intervals"),

    ("ap_stats", "general", "A", 3, "To test H₀: μ = 30 vs. Hₐ: μ > 30 with known σ=10 and n=25, the test statistic is z. If x̄=34, z = ?",
     "multiple_choice", "2.0", "1.0", "4.0", "0.4", "A",
     "z = (x̄−μ₀)/(σ/√n) = (34−30)/(10/√25) = 4/(10/5) = 4/2 = 2.0.",
     "inference_z_test"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "A t-distribution is used instead of z when:",
     "multiple_choice",
     "The population is not normal",
     "The population standard deviation σ is unknown and is estimated by s",
     "The sample size is very large",
     "The data is categorical", "B",
     "When σ is unknown, we use the sample standard deviation s and the t-distribution, which has heavier tails to account for additional uncertainty.",
     "inference_t_test"),

    ("ap_stats", "general", "U", 3, "For a paired t-test, what data do you analyze?",
     "multiple_choice",
     "The original values from each group",
     "The differences between paired observations",
     "The means of each group separately",
     "The sum of the two groups' values", "B",
     "In a paired t-test, compute d = x₁−x₂ for each pair, then test whether the mean difference μ_d = 0.",
     "inference_paired_t_test"),

    ("ap_stats", "general", "A", 4, "A 90% CI for μ uses z*≈1.645, and a 95% CI uses z*≈1.96. How does increasing confidence from 90% to 95% affect the CI?",
     "multiple_choice",
     "The interval becomes narrower",
     "The interval becomes wider",
     "The interval shifts to the right",
     "The margin of error decreases", "B",
     "Higher confidence → larger z* → larger ME = z*·(s/√n) → wider interval. More confidence costs precision.",
     "inference_confidence_intervals"),

    ("ap_stats", "general", "R", 3, "The power of a statistical test is:",
     "multiple_choice",
     "1 − α",
     "1 − β",
     "The probability of a Type I error",
     "α + β", "B",
     "Power = 1 − β = P(rejecting H₀ | H₀ is false). Higher power means better ability to detect a real effect.",
     "inference_power"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "In a chi-square goodness-of-fit test, the test statistic is χ² = Σ(O−E)²/E. Here O and E represent:",
     "multiple_choice",
     "Observed and expected frequencies",
     "Ordinary and expected values",
     "Observations and errors",
     "Original and estimated values", "A",
     "O = observed count in each category; E = expected count if H₀ is true.",
     "inference_chi_square"),

    ("ap_stats", "general", "U", 3, "A chi-square test of independence has (r−1)(c−1) degrees of freedom, where r and c are the number of rows and columns. For a 3×4 table:",
     "multiple_choice", "6", "10", "12", "11", "A",
     "df = (3−1)(4−1) = 2·3 = 6.",
     "inference_chi_square"),

    ("ap_stats", "general", "A", 4, "A chi-square test of independence is used to test:",
     "multiple_choice",
     "Whether a single categorical variable follows a specified distribution",
     "Whether two categorical variables are related in a population",
     "Whether the means of two groups are equal",
     "Whether the variance equals a specified value", "B",
     "Chi-square test of independence tests whether two categorical variables are associated or independent in the population.",
     "inference_chi_square"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "For inference on a population proportion p, the conditions required include the large counts condition: np ≥ 10 AND n(1−p) ≥ 10. This ensures:",
     "multiple_choice",
     "The sample size is large enough",
     "The sampling distribution of p̂ is approximately normal",
     "The data comes from an SRS",
     "Both A and B", "D",
     "Both conditions (large n and np≥10, n(1−p)≥10) ensure the sampling distribution of p̂ is approximately normal, enabling use of z-procedures.",
     "inference_proportion_conditions"),

    ("ap_stats", "general", "U", 4, "The 95% confidence interval for p is p̂ ± z*·√(p̂(1−p̂)/n). With p̂=0.6, n=100, z*=1.96, the interval is approximately:",
     "multiple_choice",
     "(0.504, 0.696)",
     "(0.54, 0.66)",
     "(0.508, 0.692)",
     "(0.50, 0.70)", "A",
     "ME = 1.96·√(0.6·0.4/100) = 1.96·√0.0024 = 1.96·0.04899 ≈ 0.096. CI: (0.6−0.096, 0.6+0.096) = (0.504, 0.696).",
     "inference_confidence_intervals"),

    ("ap_stats", "general", "A", 4, "A t-test for μ: H₀: μ=20 vs. Hₐ: μ≠20. With x̄=23, s=6, n=16, the test statistic t = ?",
     "multiple_choice", "2.0", "1.5", "3.0", "0.5", "A",
     "t = (x̄−μ₀)/(s/√n) = (23−20)/(6/4) = 3/(1.5) = 2.0. df=15.",
     "inference_t_test"),

    ("ap_stats", "general", "R", 3, "Increasing sample size n affects which of the following in a confidence interval for a mean?",
     "multiple_choice",
     "Increases the critical value z*",
     "Decreases the margin of error",
     "Increases the confidence level",
     "Shifts the interval center", "B",
     "ME = z*·(s/√n). As n increases, √n increases, so ME decreases → narrower interval.",
     "inference_confidence_intervals"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 2, "The null hypothesis H₀ in a test about a population mean is typically of the form:",
     "multiple_choice", "μ > μ₀", "μ ≠ μ₀", "μ = μ₀", "x̄ = μ₀", "C",
     "H₀ is always a statement of no effect or no difference, typically H₀: μ = μ₀.",
     "inference_hypothesis_tests"),

    ("ap_stats", "general", "U", 3, "Which condition must be checked before performing a one-sample t-test for μ?",
     "multiple_choice",
     "The population standard deviation is known",
     "The data comes from a random sample and the population is approximately normal (or n is large)",
     "All data values are positive",
     "The sample size exceeds 100", "B",
     "For a t-test: (1) random sample, (2) normality — either the population is normal or n ≥ 30 by CLT.",
     "inference_t_test_conditions"),

    ("ap_stats", "general", "A", 4, "A researcher calculates a p-value of 0.12 with α=0.05. The conclusion is:",
     "multiple_choice",
     "Reject H₀; there is significant evidence",
     "Fail to reject H₀; the result is not statistically significant",
     "Accept H₀; it is proven true",
     "The test is inconclusive — collect more data", "B",
     "p=0.12 > α=0.05: fail to reject H₀. This does NOT prove H₀ is true — just insufficient evidence against it.",
     "inference_hypothesis_tests"),

    ("ap_stats", "general", "R", 3, "The expected cell count in a chi-square test is calculated as:",
     "multiple_choice",
     "(Row total × Column total) / Grand total",
     "(Row total + Column total) / 2",
     "Observed count / Grand total",
     "Grand total / (rows × columns)", "A",
     "Expected count = (row total × column total) / grand total. This is what would be expected if the variables were independent.",
     "inference_chi_square"),

    ("ap_stats", "seed_ap_stats_supplement.py".replace("seed_","").replace("_supplement.py",""), "F", 3, "A test for the slope β₁ in simple linear regression uses H₀: β₁ = 0. Rejecting H₀ suggests:",
     "multiple_choice",
     "There is no linear relationship",
     "There is a statistically significant linear relationship between x and y",
     "The regression line passes through the origin",
     "The correlation is exactly 1", "B",
     "β₁=0 means no linear relationship. Rejecting H₀ means the slope is significantly different from 0 — evidence of a linear relationship.",
     "inference_regression"),

    ("ap_stats", "general", "U", 4, "In a two-sample t-test for μ₁−μ₂, H₀: μ₁=μ₂, Hₐ: μ₁>μ₂, with t=2.15 and p-value=0.02 at α=0.05, the conclusion is:",
     "multiple_choice",
     "Fail to reject H₀",
     "Reject H₀; significant evidence that μ₁ > μ₂",
     "Accept H₁ with 95% certainty",
     "Increase sample size and retest", "B",
     "p=0.02 < α=0.05: reject H₀. There is statistically significant evidence that μ₁ > μ₂.",
     "inference_two_sample_t"),

    ("ap_stats", "general", "A", 4, "A 99% confidence interval for the difference in two proportions (p₁−p₂) is (0.02, 0.18). Which conclusion is most appropriate?",
     "multiple_choice",
     "There is no significant difference at α=0.01",
     "There is significant evidence that p₁ > p₂ at α=0.01",
     "p₁ − p₂ = 0.10 with certainty",
     "The test is inconclusive without a p-value", "B",
     "The 99% CI for p₁−p₂ is (0.02, 0.18), which does not contain 0. This means at α=0.01 we have significant evidence that p₁>p₂.",
     "inference_proportion_CI"),
]

def seed():
    conn = sqlite3.connect(DB_PATH)
    inserted = 0
    for q in QUESTIONS:
        exists = conn.execute("SELECT id FROM questions WHERE question_text = ?", (q[4],)).fetchone()
        if not exists:
            conn.execute("""INSERT INTO questions (track, sat_domain, fuar_dimension, difficulty,
                question_text, question_type, option_a, option_b, option_c, option_d,
                correct_answer, explanation, topic_tag) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""", q)
            inserted += 1
    conn.commit()
    conn.close()
    print(f"[seed] supplement: {inserted} inserted")
    return inserted

if __name__ == "__main__":
    seed()
